### ISSUE TITLE
issue when I drag the map

### ISSUE THREAD

**Issue by nielk** [Wildhoney/L.Pather#1]
Hi,
First of all, you did a great job with this plugin :+1: 

But I encounter an issue : 
- open : https://pather.herokuapp.com/
- disable the pencil button (pencil)
- drag the map to move it
- enable the pencil button
- draw a path
- the created path will not be at the right place :(

Best regards,
Oger Alexandre

**Comment by Wildhoney** [comment]
Thanks! :+1: Sorry, I introduced this bug yesterday when implementing the mobile support. [Please try again](https://pather.herokuapp.com/).

**Comment by nielk** [comment]
Thanks :+1:
