### ISSUE TITLE
Edit mode - can not drag the elbow markers

### ISSUE THREAD

**Issue by jianyunli** [Wildhoney/L.Pather#11]
I can not drag the markers around in the Edit mode, the whole map would be dragging.

**Comment by Wildhoney** [comment]
Have you got it setup similar to [the example](https://pather.herokuapp.com/)? As when you have only the two middle modes active, you can pan on the map, but dragging an elbow will not propagate the event to the map.

**Comment by jianyunli** [comment]
Thanks for quick reply, I did not follow the example exactly, I don't know ReactJS... Basically I created a map, provided a tile layer and created L.Pather layer, then created several buttons and set mode to Create, Edit etc.. exclusively by clicking corresponding button.

`map.patherLayer.setMode(L.Pather.MODE[mode]`

my simple app is here
http://analysis-greenbranch.rhcloud.com/

how do I prevent dragging the elbow propagating to the map?

**Comment by Wildhoney** [comment]
I've setup [a simple JSFiddle](https://jsfiddle.net/myenkabp/) which also seems fine &mdash; at least for me. Please take a look.

**Comment by jianyunli** [comment]
Thank you, using your example, I figured out why it's not working for me. First I set the mode to ALL, it works. Then I set the mode to L.Pather.MODE.EDIT | L.Pather.MODE.CREATE and it works too, which leads me to `function shouldDisableDrag() {
return (this.options.mode & MODES.CREATE)
}`

it means if mode contains CREATE, the map dragging is disabled. Previously I set the map to CREATE, EDIT exclusively...

but I am still curious, your original example works when in the EDIT mode exclusively

**Comment by Wildhoney** [comment]
It's [also fine](https://jsfiddle.net/myenkabp/1/) when using the `CREATE` and `EDIT` modes exclusively.

The drag is disabled **only** when `CREATE` mode is active, due to the fact that you're dragging on top of the map. However when you're dragging one of the elbows, the event doesn't propagate to the map because of [`e.stopPropagation`](https://github.com/Wildhoney/L.Pather/blob/master/module/components/Polyline.js#L139). 

I'm sure you're not making the mistake, but it's worth pointing out &mdash; `EDIT` mode must be active for you to drag elbows. CSS should disable the dragging of elbows when not in `EDIT` mode.

**Comment by jianyunli** [comment]
Thanks again, very strangely `EDIT` modes exclusively does not work for me.

```
event.stopPropagation();
event.preventDefault();
```

seems not working, event continue propagated to the map

**Comment by Wildhoney** [comment]
Could you show me [your code](http://analysis-greenbranch.rhcloud.com/app.js) unminified, please?

**Comment by jianyunli** [comment]
Sorry, I forgot I use webpack to minify the build code. I build a repository at bitbucket
https://bitbucket.org/jianyunli/greenbranchjs

thanks for taking a look

**Comment by jianyunli** [comment]
Just report back what I did to fix this issue for me, I used

`event.stopImmediatePropagation()`

instead of  `event.stopPropagation()`

it worked, very strange, by documentation `stopImmediatePropagation()` will also prevent other handlers from executing, couldn't figure out what other handlers are on the marker.

Thanks
