### ISSUE TITLE
Path renders after mouse button release

### ISSUE THREAD

**Issue by bluecorridor** [Wildhoney/L.Pather#17]
Hi- hoping someone will see this. 

Added this plugin to our application, which currently has the leaflet.Draw plugin and having an issue where the polyline only renders after the mouse button is released, and not during the path creation.

Any ideas of what might be happening? or where to start poking around? I'm guessing some events are firing to halt the rendering of the line.

**Comment by bluecorridor** [comment]
Solved two issues that was causing this behavior for me:
1. Z index of the layers was lower than the tiles
2. The area defined by the svg element with class pather was not overlapping the map div

**Comment by stefanocudini** [comment]
I confirm 1. at last version this bug persist
