### ISSUE TITLE
import/webpack

### ISSUE THREAD

**Issue by felluksch** [Wildhoney/L.Pather#19]
Hi, I'm probably going to embarass myself but how do you load Pather (as a node_module) into another file (e.g. index.js) to make it work with webpack? Importing FreeDraw (as specified in its doc) works like a charm but `import 'leaflet-pather'` (and `import { Pather } from 'leaflet-pather'`) doesn't. I'm really just starting with more complex Javascript and Webpack and all, so it'd be really nice if you could give a hint :)
Thanks a lot for the effort you put into the development of FreeDraw and Pather!

**Comment by felluksch** [comment]
@Wildhoney Sorry to be obtrusive but I'm kind of depending on Pather. It seems like @ankeetmaini 's pull request will solve my problem. I copied the repo into my node_modules folder and tried to load it via `import Pather from '<module-name>'` but it isn't working, probably because I didn't install it properly via npm (?). Why isn't the pull request implemented yet? If there is anything I (as a JS beginner, but eager to learn) can do, let me know! Thanks!

**Comment by Wildhoney** [comment]
Sorry, I'm currently away @felluksch. Did you have any luck, otherwise I'll take a look on Monday, and merge the PR if all looks good.

**Comment by felluksch** [comment]
Hi, yes, @kotarella1110 made it work (see the referenced issue). Modules in JS can be quite confusing for beginners… Transitioning to ES6 modules will make things easier, I guess, but for now everything works. Thanks for getting in touch and enjoy your trip!

**Comment by Wildhoney** [comment]
Thanks @felluksch &ndash; apologies for the silence. Glad you're all good now.
