### ISSUE TITLE
removeLayer

### ISSUE THREAD

**Issue by rodrigorn** [Wildhoney/L.Pather#2]
Hi!

Thanks for your awesome work!
I'm having some trouble  removing the pather layer from my map, I want to toggle between selecting points or paths but the pather layer can't  be removed once added, or at least it keeps drawing paths, what should I do?

**Comment by Wildhoney** [comment]
Thanks, Rodrigo! :beers: 

I've added a better cleanup of the module when you invoke `onRemove`, but I imagine you want to retain the paths drawn when you remove the Pather layer? For this you could take the drawn polylines from the `create`, `edit`, `delete` events, and re-draw them using `createPath` when you re-enable the module. Alternatively &mdash; and I'll probably do this tomorrow &mdash; I'll add two methods: `enable` and `disable` to temporarily disable the Pather module :+1: 

Hopefully this is fine for now, however.

**Comment by Wildhoney** [comment]
For the time being, I've added a `removePolylines` option to retain the polylines for the `onRemove` hook. I think this should be fine, but I've not thought of any potential ramifications it might have, as it's a little late and I'm a bit tired.

Please give it a try with:

``` javascript
var pather = new L.Pather({
    removePolylines: false
});
```

**Comment by Wildhoney** [comment]
Any luck with this @rodrigorn?
