### ISSUE TITLE
Error when creating polyline from code

### ISSUE THREAD

**Issue by OlivBoo** [Wildhoney/L.Pather#3]
Hello,
I encounter a bug when creating a path from code :
http://jsfiddle.net/ykxzk1pk/6/

When I try to move the map or add a new elbow, I get the following error :
`Uncaught TypeError: Cannot read property 'map' of undefined` in pather.js at line 349

**Comment by Wildhoney** [comment]
Thanks for raising the issue :+1: Please try again with `v0.1.15` &ndash; it should work on your JSFiddle once the [Travis build has finished](https://travis-ci.org/Wildhoney/L.Pather).

**Comment by OlivBoo** [comment]
Thanks a lot :+1:

**Comment by Wildhoney** [comment]
By the way, I assume your polyline is _supposed_ to follow the roundabout and go down Avenue Victor Hugo. Is that a problem with your `latLng[]`s being slightly out, or is it a problem with `L.Pather`?

**Comment by OlivBoo** [comment]
Yes my path was following the roundabout (coordinates were generated with L.Pather), the problem seems to be with L.Pather. I updated my JSFiddle to get stringified version of the polyline when editing :
http://jsfiddle.net/ykxzk1pk/9/

**Comment by Wildhoney** [comment]
Apologies! Please re-draw your polyline with `v0.1.16` and it should re-trace the exact polyline.

**Comment by OlivBoo** [comment]
Ok thanks, when I re-trace my polyline and get the new coordinates it is correctly loaded when I refresh the browser. 
But I'm experiencing a new issue if the polyline is outside the map view when loading (see http://jsfiddle.net/ykxzk1pk/12/), i'm getting the following error :
`Uncaught TypeError: Cannot read property 'forEach' of undefined` at line 624

**Comment by Wildhoney** [comment]
Yep, that's something I had to deal with in `FreeDraw` &ndash; for the time being set `L.Path.CLIP_PADDING` to something high, such as `5000`:

``` javascript
L.Path.CLIP_PADDING = 5000;
```

It's essentially there for performance reasons, but unfortunately Leaflet doesn't offer an easy way to handle the clipping of polygons. It's certainly possible, but will take me a while, and the above will fix this particular case until I do handle this properly in `L.Pather` :+1:

**Comment by OlivBoo** [comment]
It works well for what I need to do, thank you very much :+1:
