### ISSUE TITLE
bower.json manifest "main" should refer to dist/pather.js, not dist/pather.min.js

### ISSUE THREAD

**Issue by brucecrevensten** [Wildhoney/L.Pather#4]
Pointing at the nonexistent file breaks some build toolchains (grunt-requirejs, in my case).

Thanks for an exceedingly awesome library!

**Comment by Wildhoney** [comment]
Oops! Thanks for pointing it out :+1: You're welcome!

**Comment by brucecrevensten** [comment]
Best ticket response cycle _ever_ :beer:

**Comment by Wildhoney** [comment]
:beers: !
