### ISSUE TITLE
Can not create path from existed geometry

### ISSUE THREAD

**Issue by haku-d** [Wildhoney/L.Pather#5]
Thanks for your work.

I have try this:

```
var polyline = pather.createPath(LatLng[]);
```

And no path was created.
But an error was throwed out:
**Uncaught TypeError: Cannot read property 'forEach' of undefined   pather-src.js:624** 

Anyone have same error with me ?

**Comment by Wildhoney** [comment]
Set `L.Path.CLIP_PADDING = 5000` &mdash; or **any** high number &mdash; until I fix an issue with the clipping of the polylines which are out-of-view :+1: Raised [separate ticket](https://github.com/Wildhoney/L.Pather/issues/6) to resolve.
